####################################################################################################
### small_perfect_groups.g
### 
### This program builds the linear system M_H (defined in [DSR23+, Definition 6.1]) for all small
### perfect groups H and checks whether or not this system has full column rank.
### 
### The system M_H has full column rank if and only if the homogeneous solution group Γ(M_H, 0) is
### perfect, so this program finds all perfect groups H (up to a certain size) for which the
### homogeneous solution group Γ(M_H, 0) is perfect. For brevity, we say that such groups H "work".
### 
### Remark. We note that M_H can also have full column rank if H is not perfect. However, if that
### is the case, then the subgroup of H generated by the elements of order 2 must be perfect,
### because it is a quotient of the (perfect) solution group Γ(M_H, 0). As a concrete example, let
### H = A7 x C3; then M_H is the same linear system as M_A7, so Γ(M_H, 0) is perfect even though H
### is not. Examples of this type are not minimal and therefore not the most interesting, so we
### focus on perfect groups H. This has the added benefit of significantly reducing the search
### space, since there are not so many perfect groups.
### 
### This program finds that the following perfect groups of order ≤ 10080 work:
### 
###     * PerfectGroup(2520, 1) = A7
###     * PerfectGroup(3420, 1) = L2(19)        (the projective special linear group PSL(2, 19))
###     * PerfectGroup(5616, 1) = L3(3)         (the projective special linear group PSL(3, 3))
###     * PerfectGroup(6072, 1) = L2(23)        (the projective special linear group PSL(2, 23))
###     * PerfectGroup(7560, 1) = A7 3^1        (the triple cover of A7)
###     * PerfectGroup(7800, 1) = L2(25)        (the projective special linear group PSL(2, 25))
###     * PerfectGroup(7920, 1) = M11           (the Mathieu group M11)
###     * PerfectGroup(9828, 1) = L2(27)        (the projective special linear group PSL(2, 27))
### 
### The estimated total runtime of this program is:  less than 5 seconds.
### The estimated memory usage of this program is:   default memory usage of GAP (typically 4 GB).
### 
### To extend the search, simply increase the value of the constant "max_order" to a larger value.
### 
### 
### In addition to the groups found by this program, we have the following results:
### 
###     * The proof in our paper [DRS23+] shows that the alternating group A_n works for all n ≥ 7.
###     
###     * The program "Mathieu.g" shows that the sporadic Mathieu groups M11, M12, M22, M23 and M24
###       also work, whereas the non-sporadic Mathieu subgroups M9, M10 ≤ M11 and M21 ≤ M22 do not.
###     
###     * The program "PSL2q.g" shows that the projective special linear group PSL(2, q) works for
###       all odd prime powers 19 ≤ q ≤ 349. This suggests that PSL(2, q) works for all odd prime
###       powers q ≥ 19, though we don't have a proof.
### 
### 
### References:
### 
###       [DRS23+].  Josse van Dobben de Bruyn, David E. Roberson, and Simon Schmidt.
###                  “Asymmetric graphs with quantum symmetry”.
###                  Preprint, 2023.  https://arxiv.org/abs/2311.04889
### 
####################################################################################################
# Copyright (C) 2024  J. van Dobben de Bruyn, Technical University of Denmark.
# 
# SPDX-License-Identifier: GPL-2.0-or-later
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
####################################################################################################



Read(Filename(DirectoryCurrent(),"build_sparse_F2_system_from_group.g"));

max_order := 10080;

Print("Testing all perfect groups of order ≤ ", max_order, "...\n\n");
successful_ids := [];

for n in Intersection([1..max_order], SizesPerfectGroups()) do
	for k in [1..NrPerfectGroups(n)] do
		H := PerfectGroup(n,k);
		Print("Trying PerfectGroup(", n, ",", k, ") = ", H, "... \c");
		M_H := build_sparse_F2_system_from_group(H);
		if M_H = [] then
			Print("Fail.\n");
			continue;
		fi;
		num_vars := Ncols(M_H);
		num_eqs := Nrows(M_H);
		r := Rank(TransposedSparseMat(M_H)); # with these linear systems, computing the rank turns out to be MUCH faster after first taking the transpose
		if r = num_vars then
			Print("Success!\n");
			Append(successful_ids, [[n, k]]);
		else
			Print("Fail.\n");
		fi;
	od;
od;

Print("\nSummary: the following perfect groups H of order up to ", max_order, " give rise to");
Print("\n         a linear system M_H with full column rank, so that the solution");
Print("\n         group Γ(M_H, 0) is a non-trivial perfect group:\n");
for id in successful_ids do
	Print("    PerfectGroup(", id[1], ", ", id[2], ") = ", PerfectGroup(id[1], id[2]), "\n");
od;


